server:
  port: 8078
  servlet:
    context-path: /mmcs
---
# database
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/mmcs?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
      username: vdc
      password: vdc7200#
      max-lifetime: 580000
---
# devtools
spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

---
  #thymeleaf 사용
  spring:
    thymeleaf:
      prefix: classpath:templates/
      suffix: .html
      cache: false

---
#Log
logging:
  config:
    level: INFO
    path: /opt/apache-tomcat-8.5.78/logs #/logs
    file: mmcs
    errfile: mmcs_err

---
#스케쥴 관련 : 체널 모니터링 URL, freeswitch 명령어
task:
  channel_url: http://localhost:8078/VDCFreeswitch/home_channels.vdc
  freeswitch_request_url: http://localhost:8078/VDCFreeswitch/reqcmd.vdc
  conference_cmd: luarun mmcs_lua_conference_outboundcall.lua
  conference_person_cmd: luarun mmcs_lua_conference_auto_outboundrecall.lua
  record_file_delete: false