server:
  port: 8080
  servlet:
    context-path: /
---
# database
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/mmcs?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
      username: ims
      password: vdc7200#
      max-lifetime: 580000
---
# devtools
spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
---
#Log
logging:
  config:
    level: INFO
    path: ./opt/tomcat/latest/logs #/logs
    file: mmcs
    errfile: mmcs_err