server:
  port: 8080
  servlet:
    context-path: /mmcs
---
# database
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://192.168.102.221:3306/mmcs?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
      username: vdc
      password: vdc7200#
      max-lifetime: 580000
---
# devtools
spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
---
#Log
logging:
  config:
    level: INFO
    path: /opt/tomcat/logs #/logs
    file: mmcs
    errfile: mmcs_err

---
#체널 모니터링 URL
task:
  channel_url: http://192.168.102.115:8078/VDCFreeswitch/home_channels.vdc
  freeswitch_request_url: http://192.168.102.115:8078/VDCFreeswitch/reqcmd.vdc
  conference_cmd: luarun mmcs_lua_conference_outboundcall.lua
  conference_person_cmd : luarun mmcs_lua_conference_auto_outboundrecall.lua
